import re

def clean_script(text):
    """
    Cleans the script generated by LLM for TTS.
    Removes markdown formatting, section headers, and extra whitespace.
    Splits text into short phrases based on punctuation for better subtitle timing.
    """
    # Remove **Section**: pattern
    # Example: "**引入**：你有没有..." -> "你有没有..."
    # Also handle colon variations (: or ：)
    text = re.sub(r'\*\*.*?\*\*[:：]\s*', '', text)
    
    # Remove standalone **Text** (if any)
    text = re.sub(r'\*\*.*?\*\*', '', text)

    # Remove markdown headers (#, ##)
    text = re.sub(r'#+\s*', '', text)

    # Remove empty lines and strip whitespace
    lines = [line.strip() for line in text.split('\n') if line.strip()]
    text = '\n'.join(lines)
    
    # Split by punctuation to create shorter subtitle segments
    # Punctuation to split on: ，。！？；, . ! ? ;
    # We replace punct with punct + \n to force a line break (and thus a new VTT cue)
    for punct in ["，", "。", "！", "？", "；", ",", ".", "!", "?", ";"]:
        text = text.replace(punct, punct + "\n")
        
    # Re-clean to remove any empty lines caused by multiple punctuations
    lines = [line.strip() for line in text.split('\n') if line.strip()]
    
    return '\n'.join(lines)

def parse_vtt(vtt_path):
    """
    Parses a VTT file and returns a list of subtitles.
    Format: [{'start': seconds, 'end': seconds, 'text': string}]
    """
    subs = []
    with open(vtt_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split by double newline to get blocks
    blocks = content.split('\n\n')
    
    for block in blocks:
        lines = block.strip().split('\n')
        if len(lines) >= 2:
            # Check for timing line (00:00:00.000 --> 00:00:02.000)
            timing_line = None
            text_lines = []
            
            for line in lines:
                if '-->' in line:
                    timing_line = line
                elif timing_line: # Text comes after timing
                    text_lines.append(line)
            
            if timing_line and text_lines:
                start_str, end_str = timing_line.split(' --> ')
                start = parse_time(start_str)
                end = parse_time(end_str)
                text = ' '.join(text_lines)
                
                subs.append({
                    'start': start,
                    'end': end,
                    'text': text
                })
    return subs

def parse_time(time_str):
    """
    Converts timestamp string (00:00:01.250 or 00:00:01,250) to seconds (float).
    """
    time_str = time_str.strip().replace(',', '.')
    parts = time_str.split(':')
    hours = float(parts[0])
    minutes = float(parts[1])
    seconds = float(parts[2])
    return hours * 3600 + minutes * 60 + seconds
